#!/usr/bin/env bash
set -eou pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
GRADLE_CLASSPATH_DIR="${DIR}/../../gradle-classpath"

pushd "${GRADLE_CLASSPATH_DIR}" &>/dev/null || exit
"${GRADLE_CLASSPATH_DIR}/gradlew" clean installDist
popd || exit

rsync --delete --archive --verbose "${GRADLE_CLASSPATH_DIR}/build/install/gradle-classpath/" "${DIR}/gradle-classpath/"
